//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milano.BackEnd.Business.ProxyDescuentoPicoMercancia {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VentaResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VentaResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sMensaje {
            get {
                return this.sMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeField, value) != true)) {
                    this.sMensajeField = value;
                    this.RaisePropertyChanged("sMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sError {
            get {
                return this.sErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sErrorField, value) != true)) {
                    this.sErrorField = value;
                    this.RaisePropertyChanged("sError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MercanciaResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MercanciaResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sErrorField;
        
        private decimal dPtjDescuentoField;
        
        private ulong uLSesionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sMensaje {
            get {
                return this.sMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeField, value) != true)) {
                    this.sMensajeField = value;
                    this.RaisePropertyChanged("sMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sError {
            get {
                return this.sErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sErrorField, value) != true)) {
                    this.sErrorField = value;
                    this.RaisePropertyChanged("sError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal dPtjDescuento {
            get {
                return this.dPtjDescuentoField;
            }
            set {
                if ((this.dPtjDescuentoField.Equals(value) != true)) {
                    this.dPtjDescuentoField = value;
                    this.RaisePropertyChanged("dPtjDescuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public ulong uLSesion {
            get {
                return this.uLSesionField;
            }
            set {
                if ((this.uLSesionField.Equals(value) != true)) {
                    this.uLSesionField = value;
                    this.RaisePropertyChanged("uLSesion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyDescuentoPicoMercancia.wsPicosMercanciaSoap")]
    public interface wsPicosMercanciaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sSKU del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VenderSKU", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.VenderSKUResponse VenderSKU(Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.VenderSKURequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sSKU del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarSKU", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.ConsultarSKUResponse ConsultarSKU(Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.ConsultarSKURequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VenderSKURequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VenderSKU", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.VenderSKURequestBody Body;
        
        public VenderSKURequest() {
        }
        
        public VenderSKURequest(Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.VenderSKURequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VenderSKURequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ulong uLSesion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iCantidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sSKU;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int iTransaccion;
        
        public VenderSKURequestBody() {
        }
        
        public VenderSKURequestBody(ulong uLSesion, int iCantidad, string sSKU, int iTransaccion) {
            this.uLSesion = uLSesion;
            this.iCantidad = iCantidad;
            this.sSKU = sSKU;
            this.iTransaccion = iTransaccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VenderSKUResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VenderSKUResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.VenderSKUResponseBody Body;
        
        public VenderSKUResponse() {
        }
        
        public VenderSKUResponse(Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.VenderSKUResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VenderSKUResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.VentaResponse VenderSKUResult;
        
        public VenderSKUResponseBody() {
        }
        
        public VenderSKUResponseBody(Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.VentaResponse VenderSKUResult) {
            this.VenderSKUResult = VenderSKUResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarSKURequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarSKU", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.ConsultarSKURequestBody Body;
        
        public ConsultarSKURequest() {
        }
        
        public ConsultarSKURequest(Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.ConsultarSKURequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarSKURequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int iTienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iCaja;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int iCajero;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int iCantidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sSKU;
        
        public ConsultarSKURequestBody() {
        }
        
        public ConsultarSKURequestBody(int iTienda, int iCaja, int iCajero, int iCantidad, string sSKU) {
            this.iTienda = iTienda;
            this.iCaja = iCaja;
            this.iCajero = iCajero;
            this.iCantidad = iCantidad;
            this.sSKU = sSKU;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarSKUResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarSKUResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.ConsultarSKUResponseBody Body;
        
        public ConsultarSKUResponse() {
        }
        
        public ConsultarSKUResponse(Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.ConsultarSKUResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarSKUResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.MercanciaResponse ConsultarSKUResult;
        
        public ConsultarSKUResponseBody() {
        }
        
        public ConsultarSKUResponseBody(Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.MercanciaResponse ConsultarSKUResult) {
            this.ConsultarSKUResult = ConsultarSKUResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsPicosMercanciaSoapChannel : Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.wsPicosMercanciaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsPicosMercanciaSoapClient : System.ServiceModel.ClientBase<Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.wsPicosMercanciaSoap>, Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.wsPicosMercanciaSoap {
        
        public wsPicosMercanciaSoapClient() {
        }
        
        public wsPicosMercanciaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsPicosMercanciaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsPicosMercanciaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsPicosMercanciaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.VenderSKUResponse Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.wsPicosMercanciaSoap.VenderSKU(Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.VenderSKURequest request) {
            return base.Channel.VenderSKU(request);
        }
        
        public Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.VentaResponse VenderSKU(ulong uLSesion, int iCantidad, string sSKU, int iTransaccion) {
            Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.VenderSKURequest inValue = new Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.VenderSKURequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.VenderSKURequestBody();
            inValue.Body.uLSesion = uLSesion;
            inValue.Body.iCantidad = iCantidad;
            inValue.Body.sSKU = sSKU;
            inValue.Body.iTransaccion = iTransaccion;
            Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.VenderSKUResponse retVal = ((Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.wsPicosMercanciaSoap)(this)).VenderSKU(inValue);
            return retVal.Body.VenderSKUResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.ConsultarSKUResponse Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.wsPicosMercanciaSoap.ConsultarSKU(Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.ConsultarSKURequest request) {
            return base.Channel.ConsultarSKU(request);
        }
        
        public Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.MercanciaResponse ConsultarSKU(int iTienda, int iCaja, int iCajero, int iCantidad, string sSKU) {
            Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.ConsultarSKURequest inValue = new Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.ConsultarSKURequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.ConsultarSKURequestBody();
            inValue.Body.iTienda = iTienda;
            inValue.Body.iCaja = iCaja;
            inValue.Body.iCajero = iCajero;
            inValue.Body.iCantidad = iCantidad;
            inValue.Body.sSKU = sSKU;
            Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.ConsultarSKUResponse retVal = ((Milano.BackEnd.Business.ProxyDescuentoPicoMercancia.wsPicosMercanciaSoap)(this)).ConsultarSKU(inValue);
            return retVal.Body.ConsultarSKUResult;
        }
    }
}
