//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milano.BackEnd.Business.ProxyCupones {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeField;
        
        private System.DateTime dtFechaField;
        
        private decimal dSaldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sEstatusField;
        
        private int iTiendaVendidaField;
        
        private int iCodigoPromocionField;
        
        private ulong lSesionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sError {
            get {
                return this.sErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sErrorField, value) != true)) {
                    this.sErrorField = value;
                    this.RaisePropertyChanged("sError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sMensaje {
            get {
                return this.sMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeField, value) != true)) {
                    this.sMensajeField = value;
                    this.RaisePropertyChanged("sMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime dtFecha {
            get {
                return this.dtFechaField;
            }
            set {
                if ((this.dtFechaField.Equals(value) != true)) {
                    this.dtFechaField = value;
                    this.RaisePropertyChanged("dtFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal dSaldo {
            get {
                return this.dSaldoField;
            }
            set {
                if ((this.dSaldoField.Equals(value) != true)) {
                    this.dSaldoField = value;
                    this.RaisePropertyChanged("dSaldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sEstatus {
            get {
                return this.sEstatusField;
            }
            set {
                if ((object.ReferenceEquals(this.sEstatusField, value) != true)) {
                    this.sEstatusField = value;
                    this.RaisePropertyChanged("sEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int iTiendaVendida {
            get {
                return this.iTiendaVendidaField;
            }
            set {
                if ((this.iTiendaVendidaField.Equals(value) != true)) {
                    this.iTiendaVendidaField = value;
                    this.RaisePropertyChanged("iTiendaVendida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int iCodigoPromocion {
            get {
                return this.iCodigoPromocionField;
            }
            set {
                if ((this.iCodigoPromocionField.Equals(value) != true)) {
                    this.iCodigoPromocionField = value;
                    this.RaisePropertyChanged("iCodigoPromocion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public ulong lSesion {
            get {
                return this.lSesionField;
            }
            set {
                if ((this.lSesionField.Equals(value) != true)) {
                    this.lSesionField = value;
                    this.RaisePropertyChanged("lSesion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCupones.wsCuponesSoap")]
    public interface wsCuponesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento FolioCupon del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaCupon", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyCupones.ConsultaCuponResponse ConsultaCupon(Milano.BackEnd.Business.ProxyCupones.ConsultaCuponRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento folioVenta del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RealizarVenta", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyCupones.RealizarVentaResponse RealizarVenta(Milano.BackEnd.Business.ProxyCupones.RealizarVentaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaCuponRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaCupon", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyCupones.ConsultaCuponRequestBody Body;
        
        public ConsultaCuponRequest() {
        }
        
        public ConsultaCuponRequest(Milano.BackEnd.Business.ProxyCupones.ConsultaCuponRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaCuponRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigoTienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int codigoCaja;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FolioCupon;
        
        public ConsultaCuponRequestBody() {
        }
        
        public ConsultaCuponRequestBody(int codigoTienda, int codigoCaja, string FolioCupon) {
            this.codigoTienda = codigoTienda;
            this.codigoCaja = codigoCaja;
            this.FolioCupon = FolioCupon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaCuponResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaCuponResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyCupones.ConsultaCuponResponseBody Body;
        
        public ConsultaCuponResponse() {
        }
        
        public ConsultaCuponResponse(Milano.BackEnd.Business.ProxyCupones.ConsultaCuponResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaCuponResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Milano.BackEnd.Business.ProxyCupones.Respuesta ConsultaCuponResult;
        
        public ConsultaCuponResponseBody() {
        }
        
        public ConsultaCuponResponseBody(Milano.BackEnd.Business.ProxyCupones.Respuesta ConsultaCuponResult) {
            this.ConsultaCuponResult = ConsultaCuponResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RealizarVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RealizarVenta", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyCupones.RealizarVentaRequestBody Body;
        
        public RealizarVentaRequest() {
        }
        
        public RealizarVentaRequest(Milano.BackEnd.Business.ProxyCupones.RealizarVentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RealizarVentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigoTienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int codigoCaja;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int codigoTipoTrxCab;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folioVenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int codigoCajero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string folioCupon;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int transaccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal importe;
        
        public RealizarVentaRequestBody() {
        }
        
        public RealizarVentaRequestBody(int codigoTienda, int codigoCaja, int codigoTipoTrxCab, string folioVenta, int codigoCajero, string folioCupon, int transaccion, decimal importe) {
            this.codigoTienda = codigoTienda;
            this.codigoCaja = codigoCaja;
            this.codigoTipoTrxCab = codigoTipoTrxCab;
            this.folioVenta = folioVenta;
            this.codigoCajero = codigoCajero;
            this.folioCupon = folioCupon;
            this.transaccion = transaccion;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RealizarVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RealizarVentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyCupones.RealizarVentaResponseBody Body;
        
        public RealizarVentaResponse() {
        }
        
        public RealizarVentaResponse(Milano.BackEnd.Business.ProxyCupones.RealizarVentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RealizarVentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Milano.BackEnd.Business.ProxyCupones.Respuesta RealizarVentaResult;
        
        public RealizarVentaResponseBody() {
        }
        
        public RealizarVentaResponseBody(Milano.BackEnd.Business.ProxyCupones.Respuesta RealizarVentaResult) {
            this.RealizarVentaResult = RealizarVentaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsCuponesSoapChannel : Milano.BackEnd.Business.ProxyCupones.wsCuponesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsCuponesSoapClient : System.ServiceModel.ClientBase<Milano.BackEnd.Business.ProxyCupones.wsCuponesSoap>, Milano.BackEnd.Business.ProxyCupones.wsCuponesSoap {
        
        public wsCuponesSoapClient() {
        }
        
        public wsCuponesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsCuponesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCuponesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCuponesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyCupones.ConsultaCuponResponse Milano.BackEnd.Business.ProxyCupones.wsCuponesSoap.ConsultaCupon(Milano.BackEnd.Business.ProxyCupones.ConsultaCuponRequest request) {
            return base.Channel.ConsultaCupon(request);
        }
        
        public Milano.BackEnd.Business.ProxyCupones.Respuesta ConsultaCupon(int codigoTienda, int codigoCaja, string FolioCupon) {
            Milano.BackEnd.Business.ProxyCupones.ConsultaCuponRequest inValue = new Milano.BackEnd.Business.ProxyCupones.ConsultaCuponRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyCupones.ConsultaCuponRequestBody();
            inValue.Body.codigoTienda = codigoTienda;
            inValue.Body.codigoCaja = codigoCaja;
            inValue.Body.FolioCupon = FolioCupon;
            Milano.BackEnd.Business.ProxyCupones.ConsultaCuponResponse retVal = ((Milano.BackEnd.Business.ProxyCupones.wsCuponesSoap)(this)).ConsultaCupon(inValue);
            return retVal.Body.ConsultaCuponResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyCupones.RealizarVentaResponse Milano.BackEnd.Business.ProxyCupones.wsCuponesSoap.RealizarVenta(Milano.BackEnd.Business.ProxyCupones.RealizarVentaRequest request) {
            return base.Channel.RealizarVenta(request);
        }
        
        public Milano.BackEnd.Business.ProxyCupones.Respuesta RealizarVenta(int codigoTienda, int codigoCaja, int codigoTipoTrxCab, string folioVenta, int codigoCajero, string folioCupon, int transaccion, decimal importe) {
            Milano.BackEnd.Business.ProxyCupones.RealizarVentaRequest inValue = new Milano.BackEnd.Business.ProxyCupones.RealizarVentaRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyCupones.RealizarVentaRequestBody();
            inValue.Body.codigoTienda = codigoTienda;
            inValue.Body.codigoCaja = codigoCaja;
            inValue.Body.codigoTipoTrxCab = codigoTipoTrxCab;
            inValue.Body.folioVenta = folioVenta;
            inValue.Body.codigoCajero = codigoCajero;
            inValue.Body.folioCupon = folioCupon;
            inValue.Body.transaccion = transaccion;
            inValue.Body.importe = importe;
            Milano.BackEnd.Business.ProxyCupones.RealizarVentaResponse retVal = ((Milano.BackEnd.Business.ProxyCupones.wsCuponesSoap)(this)).RealizarVenta(inValue);
            return retVal.Body.RealizarVentaResult;
        }
    }
}
