//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milano.BackEnd.Business.ProxyNotaCredito {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeField;
        
        private System.DateTime dtFechaField;
        
        private decimal dSaldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sEstatusField;
        
        private int iTiendaVendidaField;
        
        private ulong lSesionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sError {
            get {
                return this.sErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sErrorField, value) != true)) {
                    this.sErrorField = value;
                    this.RaisePropertyChanged("sError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sMensaje {
            get {
                return this.sMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeField, value) != true)) {
                    this.sMensajeField = value;
                    this.RaisePropertyChanged("sMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime dtFecha {
            get {
                return this.dtFechaField;
            }
            set {
                if ((this.dtFechaField.Equals(value) != true)) {
                    this.dtFechaField = value;
                    this.RaisePropertyChanged("dtFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal dSaldo {
            get {
                return this.dSaldoField;
            }
            set {
                if ((this.dSaldoField.Equals(value) != true)) {
                    this.dSaldoField = value;
                    this.RaisePropertyChanged("dSaldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sEstatus {
            get {
                return this.sEstatusField;
            }
            set {
                if ((object.ReferenceEquals(this.sEstatusField, value) != true)) {
                    this.sEstatusField = value;
                    this.RaisePropertyChanged("sEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int iTiendaVendida {
            get {
                return this.iTiendaVendidaField;
            }
            set {
                if ((this.iTiendaVendidaField.Equals(value) != true)) {
                    this.iTiendaVendidaField = value;
                    this.RaisePropertyChanged("iTiendaVendida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public ulong lSesion {
            get {
                return this.lSesionField;
            }
            set {
                if ((this.lSesionField.Equals(value) != true)) {
                    this.lSesionField = value;
                    this.RaisePropertyChanged("lSesion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerificacionTransferenciaResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VerificacionTransferenciaResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sError {
            get {
                return this.sErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sErrorField, value) != true)) {
                    this.sErrorField = value;
                    this.RaisePropertyChanged("sError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sMensaje {
            get {
                return this.sMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeField, value) != true)) {
                    this.sMensajeField = value;
                    this.RaisePropertyChanged("sMensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyNotaCredito.wsNotaCreditoSoap")]
    public interface wsNotaCreditoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento FolioCupon del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaNota", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyNotaCredito.ConsultaNotaResponse ConsultaNota(Milano.BackEnd.Business.ProxyNotaCredito.ConsultaNotaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento codigoTipoTrxCab del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RealizarVenta", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyNotaCredito.RealizarVentaResponse RealizarVenta(Milano.BackEnd.Business.ProxyNotaCredito.RealizarVentaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCodeAlgorithm", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyNotaCredito.getCodeAlgorithmResponse getCodeAlgorithm(Milano.BackEnd.Business.ProxyNotaCredito.getCodeAlgorithmRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento referencia del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificaTransferenciaBancaria", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyNotaCredito.VerificaTransferenciaBancariaResponse VerificaTransferenciaBancaria(Milano.BackEnd.Business.ProxyNotaCredito.VerificaTransferenciaBancariaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento folioVenta del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AplicaTransferenciaBancaria", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyNotaCredito.AplicaTransferenciaBancariaResponse AplicaTransferenciaBancaria(Milano.BackEnd.Business.ProxyNotaCredito.AplicaTransferenciaBancariaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaNotaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaNota", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyNotaCredito.ConsultaNotaRequestBody Body;
        
        public ConsultaNotaRequest() {
        }
        
        public ConsultaNotaRequest(Milano.BackEnd.Business.ProxyNotaCredito.ConsultaNotaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaNotaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigoTienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int codigoCaja;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FolioCupon;
        
        public ConsultaNotaRequestBody() {
        }
        
        public ConsultaNotaRequestBody(int codigoTienda, int codigoCaja, string FolioCupon) {
            this.codigoTienda = codigoTienda;
            this.codigoCaja = codigoCaja;
            this.FolioCupon = FolioCupon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaNotaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaNotaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyNotaCredito.ConsultaNotaResponseBody Body;
        
        public ConsultaNotaResponse() {
        }
        
        public ConsultaNotaResponse(Milano.BackEnd.Business.ProxyNotaCredito.ConsultaNotaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaNotaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Milano.BackEnd.Business.ProxyNotaCredito.Respuesta ConsultaNotaResult;
        
        public ConsultaNotaResponseBody() {
        }
        
        public ConsultaNotaResponseBody(Milano.BackEnd.Business.ProxyNotaCredito.Respuesta ConsultaNotaResult) {
            this.ConsultaNotaResult = ConsultaNotaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RealizarVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RealizarVenta", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyNotaCredito.RealizarVentaRequestBody Body;
        
        public RealizarVentaRequest() {
        }
        
        public RealizarVentaRequest(Milano.BackEnd.Business.ProxyNotaCredito.RealizarVentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RealizarVentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigoTienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int codigoCaja;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string codigoTipoTrxCab;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folioVenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int codigoCajero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string folioCupon;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int transaccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal importe;
        
        public RealizarVentaRequestBody() {
        }
        
        public RealizarVentaRequestBody(int codigoTienda, int codigoCaja, string codigoTipoTrxCab, string folioVenta, int codigoCajero, string folioCupon, int transaccion, decimal importe) {
            this.codigoTienda = codigoTienda;
            this.codigoCaja = codigoCaja;
            this.codigoTipoTrxCab = codigoTipoTrxCab;
            this.folioVenta = folioVenta;
            this.codigoCajero = codigoCajero;
            this.folioCupon = folioCupon;
            this.transaccion = transaccion;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RealizarVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RealizarVentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyNotaCredito.RealizarVentaResponseBody Body;
        
        public RealizarVentaResponse() {
        }
        
        public RealizarVentaResponse(Milano.BackEnd.Business.ProxyNotaCredito.RealizarVentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RealizarVentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Milano.BackEnd.Business.ProxyNotaCredito.Respuesta RealizarVentaResult;
        
        public RealizarVentaResponseBody() {
        }
        
        public RealizarVentaResponseBody(Milano.BackEnd.Business.ProxyNotaCredito.Respuesta RealizarVentaResult) {
            this.RealizarVentaResult = RealizarVentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCodeAlgorithmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCodeAlgorithm", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyNotaCredito.getCodeAlgorithmRequestBody Body;
        
        public getCodeAlgorithmRequest() {
        }
        
        public getCodeAlgorithmRequest(Milano.BackEnd.Business.ProxyNotaCredito.getCodeAlgorithmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCodeAlgorithmRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechadate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long tienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int caja;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int folio;
        
        public getCodeAlgorithmRequestBody() {
        }
        
        public getCodeAlgorithmRequestBody(string fecha, string fechadate, long tienda, int caja, int folio) {
            this.fecha = fecha;
            this.fechadate = fechadate;
            this.tienda = tienda;
            this.caja = caja;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCodeAlgorithmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCodeAlgorithmResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyNotaCredito.getCodeAlgorithmResponseBody Body;
        
        public getCodeAlgorithmResponse() {
        }
        
        public getCodeAlgorithmResponse(Milano.BackEnd.Business.ProxyNotaCredito.getCodeAlgorithmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCodeAlgorithmResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getCodeAlgorithmResult;
        
        public getCodeAlgorithmResponseBody() {
        }
        
        public getCodeAlgorithmResponseBody(string getCodeAlgorithmResult) {
            this.getCodeAlgorithmResult = getCodeAlgorithmResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificaTransferenciaBancariaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificaTransferenciaBancaria", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyNotaCredito.VerificaTransferenciaBancariaRequestBody Body;
        
        public VerificaTransferenciaBancariaRequest() {
        }
        
        public VerificaTransferenciaBancariaRequest(Milano.BackEnd.Business.ProxyNotaCredito.VerificaTransferenciaBancariaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificaTransferenciaBancariaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigoTienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal importeVenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string referencia;
        
        public VerificaTransferenciaBancariaRequestBody() {
        }
        
        public VerificaTransferenciaBancariaRequestBody(int codigoTienda, decimal importeVenta, string referencia) {
            this.codigoTienda = codigoTienda;
            this.importeVenta = importeVenta;
            this.referencia = referencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificaTransferenciaBancariaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificaTransferenciaBancariaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyNotaCredito.VerificaTransferenciaBancariaResponseBody Body;
        
        public VerificaTransferenciaBancariaResponse() {
        }
        
        public VerificaTransferenciaBancariaResponse(Milano.BackEnd.Business.ProxyNotaCredito.VerificaTransferenciaBancariaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificaTransferenciaBancariaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Milano.BackEnd.Business.ProxyNotaCredito.VerificacionTransferenciaResponse VerificaTransferenciaBancariaResult;
        
        public VerificaTransferenciaBancariaResponseBody() {
        }
        
        public VerificaTransferenciaBancariaResponseBody(Milano.BackEnd.Business.ProxyNotaCredito.VerificacionTransferenciaResponse VerificaTransferenciaBancariaResult) {
            this.VerificaTransferenciaBancariaResult = VerificaTransferenciaBancariaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AplicaTransferenciaBancariaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AplicaTransferenciaBancaria", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyNotaCredito.AplicaTransferenciaBancariaRequestBody Body;
        
        public AplicaTransferenciaBancariaRequest() {
        }
        
        public AplicaTransferenciaBancariaRequest(Milano.BackEnd.Business.ProxyNotaCredito.AplicaTransferenciaBancariaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AplicaTransferenciaBancariaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigoTienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal importeVenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int codigoEmpleado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folioVenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string referencia;
        
        public AplicaTransferenciaBancariaRequestBody() {
        }
        
        public AplicaTransferenciaBancariaRequestBody(int codigoTienda, decimal importeVenta, int codigoEmpleado, string folioVenta, string referencia) {
            this.codigoTienda = codigoTienda;
            this.importeVenta = importeVenta;
            this.codigoEmpleado = codigoEmpleado;
            this.folioVenta = folioVenta;
            this.referencia = referencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AplicaTransferenciaBancariaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AplicaTransferenciaBancariaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyNotaCredito.AplicaTransferenciaBancariaResponseBody Body;
        
        public AplicaTransferenciaBancariaResponse() {
        }
        
        public AplicaTransferenciaBancariaResponse(Milano.BackEnd.Business.ProxyNotaCredito.AplicaTransferenciaBancariaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AplicaTransferenciaBancariaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Milano.BackEnd.Business.ProxyNotaCredito.VerificacionTransferenciaResponse AplicaTransferenciaBancariaResult;
        
        public AplicaTransferenciaBancariaResponseBody() {
        }
        
        public AplicaTransferenciaBancariaResponseBody(Milano.BackEnd.Business.ProxyNotaCredito.VerificacionTransferenciaResponse AplicaTransferenciaBancariaResult) {
            this.AplicaTransferenciaBancariaResult = AplicaTransferenciaBancariaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsNotaCreditoSoapChannel : Milano.BackEnd.Business.ProxyNotaCredito.wsNotaCreditoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsNotaCreditoSoapClient : System.ServiceModel.ClientBase<Milano.BackEnd.Business.ProxyNotaCredito.wsNotaCreditoSoap>, Milano.BackEnd.Business.ProxyNotaCredito.wsNotaCreditoSoap {
        
        public wsNotaCreditoSoapClient() {
        }
        
        public wsNotaCreditoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsNotaCreditoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsNotaCreditoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsNotaCreditoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyNotaCredito.ConsultaNotaResponse Milano.BackEnd.Business.ProxyNotaCredito.wsNotaCreditoSoap.ConsultaNota(Milano.BackEnd.Business.ProxyNotaCredito.ConsultaNotaRequest request) {
            return base.Channel.ConsultaNota(request);
        }
        
        public Milano.BackEnd.Business.ProxyNotaCredito.Respuesta ConsultaNota(int codigoTienda, int codigoCaja, string FolioCupon) {
            Milano.BackEnd.Business.ProxyNotaCredito.ConsultaNotaRequest inValue = new Milano.BackEnd.Business.ProxyNotaCredito.ConsultaNotaRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyNotaCredito.ConsultaNotaRequestBody();
            inValue.Body.codigoTienda = codigoTienda;
            inValue.Body.codigoCaja = codigoCaja;
            inValue.Body.FolioCupon = FolioCupon;
            Milano.BackEnd.Business.ProxyNotaCredito.ConsultaNotaResponse retVal = ((Milano.BackEnd.Business.ProxyNotaCredito.wsNotaCreditoSoap)(this)).ConsultaNota(inValue);
            return retVal.Body.ConsultaNotaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyNotaCredito.RealizarVentaResponse Milano.BackEnd.Business.ProxyNotaCredito.wsNotaCreditoSoap.RealizarVenta(Milano.BackEnd.Business.ProxyNotaCredito.RealizarVentaRequest request) {
            return base.Channel.RealizarVenta(request);
        }
        
        public Milano.BackEnd.Business.ProxyNotaCredito.Respuesta RealizarVenta(int codigoTienda, int codigoCaja, string codigoTipoTrxCab, string folioVenta, int codigoCajero, string folioCupon, int transaccion, decimal importe) {
            Milano.BackEnd.Business.ProxyNotaCredito.RealizarVentaRequest inValue = new Milano.BackEnd.Business.ProxyNotaCredito.RealizarVentaRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyNotaCredito.RealizarVentaRequestBody();
            inValue.Body.codigoTienda = codigoTienda;
            inValue.Body.codigoCaja = codigoCaja;
            inValue.Body.codigoTipoTrxCab = codigoTipoTrxCab;
            inValue.Body.folioVenta = folioVenta;
            inValue.Body.codigoCajero = codigoCajero;
            inValue.Body.folioCupon = folioCupon;
            inValue.Body.transaccion = transaccion;
            inValue.Body.importe = importe;
            Milano.BackEnd.Business.ProxyNotaCredito.RealizarVentaResponse retVal = ((Milano.BackEnd.Business.ProxyNotaCredito.wsNotaCreditoSoap)(this)).RealizarVenta(inValue);
            return retVal.Body.RealizarVentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyNotaCredito.getCodeAlgorithmResponse Milano.BackEnd.Business.ProxyNotaCredito.wsNotaCreditoSoap.getCodeAlgorithm(Milano.BackEnd.Business.ProxyNotaCredito.getCodeAlgorithmRequest request) {
            return base.Channel.getCodeAlgorithm(request);
        }
        
        public string getCodeAlgorithm(string fecha, string fechadate, long tienda, int caja, int folio) {
            Milano.BackEnd.Business.ProxyNotaCredito.getCodeAlgorithmRequest inValue = new Milano.BackEnd.Business.ProxyNotaCredito.getCodeAlgorithmRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyNotaCredito.getCodeAlgorithmRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.fechadate = fechadate;
            inValue.Body.tienda = tienda;
            inValue.Body.caja = caja;
            inValue.Body.folio = folio;
            Milano.BackEnd.Business.ProxyNotaCredito.getCodeAlgorithmResponse retVal = ((Milano.BackEnd.Business.ProxyNotaCredito.wsNotaCreditoSoap)(this)).getCodeAlgorithm(inValue);
            return retVal.Body.getCodeAlgorithmResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyNotaCredito.VerificaTransferenciaBancariaResponse Milano.BackEnd.Business.ProxyNotaCredito.wsNotaCreditoSoap.VerificaTransferenciaBancaria(Milano.BackEnd.Business.ProxyNotaCredito.VerificaTransferenciaBancariaRequest request) {
            return base.Channel.VerificaTransferenciaBancaria(request);
        }
        
        public Milano.BackEnd.Business.ProxyNotaCredito.VerificacionTransferenciaResponse VerificaTransferenciaBancaria(int codigoTienda, decimal importeVenta, string referencia) {
            Milano.BackEnd.Business.ProxyNotaCredito.VerificaTransferenciaBancariaRequest inValue = new Milano.BackEnd.Business.ProxyNotaCredito.VerificaTransferenciaBancariaRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyNotaCredito.VerificaTransferenciaBancariaRequestBody();
            inValue.Body.codigoTienda = codigoTienda;
            inValue.Body.importeVenta = importeVenta;
            inValue.Body.referencia = referencia;
            Milano.BackEnd.Business.ProxyNotaCredito.VerificaTransferenciaBancariaResponse retVal = ((Milano.BackEnd.Business.ProxyNotaCredito.wsNotaCreditoSoap)(this)).VerificaTransferenciaBancaria(inValue);
            return retVal.Body.VerificaTransferenciaBancariaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyNotaCredito.AplicaTransferenciaBancariaResponse Milano.BackEnd.Business.ProxyNotaCredito.wsNotaCreditoSoap.AplicaTransferenciaBancaria(Milano.BackEnd.Business.ProxyNotaCredito.AplicaTransferenciaBancariaRequest request) {
            return base.Channel.AplicaTransferenciaBancaria(request);
        }
        
        public Milano.BackEnd.Business.ProxyNotaCredito.VerificacionTransferenciaResponse AplicaTransferenciaBancaria(int codigoTienda, decimal importeVenta, int codigoEmpleado, string folioVenta, string referencia) {
            Milano.BackEnd.Business.ProxyNotaCredito.AplicaTransferenciaBancariaRequest inValue = new Milano.BackEnd.Business.ProxyNotaCredito.AplicaTransferenciaBancariaRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyNotaCredito.AplicaTransferenciaBancariaRequestBody();
            inValue.Body.codigoTienda = codigoTienda;
            inValue.Body.importeVenta = importeVenta;
            inValue.Body.codigoEmpleado = codigoEmpleado;
            inValue.Body.folioVenta = folioVenta;
            inValue.Body.referencia = referencia;
            Milano.BackEnd.Business.ProxyNotaCredito.AplicaTransferenciaBancariaResponse retVal = ((Milano.BackEnd.Business.ProxyNotaCredito.wsNotaCreditoSoap)(this)).AplicaTransferenciaBancaria(inValue);
            return retVal.Body.AplicaTransferenciaBancariaResult;
        }
    }
}
