//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milano.BackEnd.Business.ProxyVentaEmpleado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoVenta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class InfoVenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeField;
        
        private System.Guid gSesionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sError {
            get {
                return this.sErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sErrorField, value) != true)) {
                    this.sErrorField = value;
                    this.RaisePropertyChanged("sError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sMensaje {
            get {
                return this.sMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeField, value) != true)) {
                    this.sMensajeField = value;
                    this.RaisePropertyChanged("sMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Guid gSesion {
            get {
                return this.gSesionField;
            }
            set {
                if ((this.gSesionField.Equals(value) != true)) {
                    this.gSesionField = value;
                    this.RaisePropertyChanged("gSesion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoEmpleado", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class InfoEmpleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNombreField;
        
        private double dCreditoField;
        
        private long iNumeroNominaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sError {
            get {
                return this.sErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sErrorField, value) != true)) {
                    this.sErrorField = value;
                    this.RaisePropertyChanged("sError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sMensaje {
            get {
                return this.sMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeField, value) != true)) {
                    this.sMensajeField = value;
                    this.RaisePropertyChanged("sMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sPaterno {
            get {
                return this.sPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.sPaternoField, value) != true)) {
                    this.sPaternoField = value;
                    this.RaisePropertyChanged("sPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sMaterno {
            get {
                return this.sMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.sMaternoField, value) != true)) {
                    this.sMaternoField = value;
                    this.RaisePropertyChanged("sMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sNombre {
            get {
                return this.sNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.sNombreField, value) != true)) {
                    this.sNombreField = value;
                    this.RaisePropertyChanged("sNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double dCredito {
            get {
                return this.dCreditoField;
            }
            set {
                if ((this.dCreditoField.Equals(value) != true)) {
                    this.dCreditoField = value;
                    this.RaisePropertyChanged("dCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public long iNumeroNomina {
            get {
                return this.iNumeroNominaField;
            }
            set {
                if ((this.iNumeroNominaField.Equals(value) != true)) {
                    this.iNumeroNominaField = value;
                    this.RaisePropertyChanged("iNumeroNomina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyVentaEmpleado.wsVentaEmpleadoSoap")]
    public interface wsVentaEmpleadoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento numeroNomina del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RealizarVenta", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyVentaEmpleado.RealizarVentaResponse RealizarVenta(Milano.BackEnd.Business.ProxyVentaEmpleado.RealizarVentaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento numeroNomina del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarEmpleado", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoResponse ConsultarEmpleado(Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento numeroNomina del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarEmpleadoTCMM", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoTCMMResponse ConsultarEmpleadoTCMM(Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoTCMMRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RealizarVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RealizarVenta", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyVentaEmpleado.RealizarVentaRequestBody Body;
        
        public RealizarVentaRequest() {
        }
        
        public RealizarVentaRequest(Milano.BackEnd.Business.ProxyVentaEmpleado.RealizarVentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RealizarVentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigoEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numeroNomina;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int codigoTienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int codigoCaja;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double montoVenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double montoFinanciado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string folioVenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int codigoTransaccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime fechaVenta;
        
        public RealizarVentaRequestBody() {
        }
        
        public RealizarVentaRequestBody(int codigoEmpresa, string numeroNomina, int codigoTienda, int codigoCaja, double montoVenta, double montoFinanciado, string folioVenta, int codigoTransaccion, System.DateTime fechaVenta) {
            this.codigoEmpresa = codigoEmpresa;
            this.numeroNomina = numeroNomina;
            this.codigoTienda = codigoTienda;
            this.codigoCaja = codigoCaja;
            this.montoVenta = montoVenta;
            this.montoFinanciado = montoFinanciado;
            this.folioVenta = folioVenta;
            this.codigoTransaccion = codigoTransaccion;
            this.fechaVenta = fechaVenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RealizarVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RealizarVentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyVentaEmpleado.RealizarVentaResponseBody Body;
        
        public RealizarVentaResponse() {
        }
        
        public RealizarVentaResponse(Milano.BackEnd.Business.ProxyVentaEmpleado.RealizarVentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RealizarVentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Milano.BackEnd.Business.ProxyVentaEmpleado.InfoVenta RealizarVentaResult;
        
        public RealizarVentaResponseBody() {
        }
        
        public RealizarVentaResponseBody(Milano.BackEnd.Business.ProxyVentaEmpleado.InfoVenta RealizarVentaResult) {
            this.RealizarVentaResult = RealizarVentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarEmpleado", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoRequestBody Body;
        
        public ConsultarEmpleadoRequest() {
        }
        
        public ConsultarEmpleadoRequest(Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarEmpleadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigoEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numeroNomina;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int codigoTienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int codigoCaja;
        
        public ConsultarEmpleadoRequestBody() {
        }
        
        public ConsultarEmpleadoRequestBody(int codigoEmpresa, string numeroNomina, int codigoTienda, int codigoCaja) {
            this.codigoEmpresa = codigoEmpresa;
            this.numeroNomina = numeroNomina;
            this.codigoTienda = codigoTienda;
            this.codigoCaja = codigoCaja;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarEmpleadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoResponseBody Body;
        
        public ConsultarEmpleadoResponse() {
        }
        
        public ConsultarEmpleadoResponse(Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarEmpleadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Milano.BackEnd.Business.ProxyVentaEmpleado.InfoEmpleado ConsultarEmpleadoResult;
        
        public ConsultarEmpleadoResponseBody() {
        }
        
        public ConsultarEmpleadoResponseBody(Milano.BackEnd.Business.ProxyVentaEmpleado.InfoEmpleado ConsultarEmpleadoResult) {
            this.ConsultarEmpleadoResult = ConsultarEmpleadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarEmpleadoTCMMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarEmpleadoTCMM", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoTCMMRequestBody Body;
        
        public ConsultarEmpleadoTCMMRequest() {
        }
        
        public ConsultarEmpleadoTCMMRequest(Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoTCMMRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarEmpleadoTCMMRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigoEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numeroNomina;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int codigoTienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int codigoCaja;
        
        public ConsultarEmpleadoTCMMRequestBody() {
        }
        
        public ConsultarEmpleadoTCMMRequestBody(int codigoEmpresa, string numeroNomina, int codigoTienda, int codigoCaja) {
            this.codigoEmpresa = codigoEmpresa;
            this.numeroNomina = numeroNomina;
            this.codigoTienda = codigoTienda;
            this.codigoCaja = codigoCaja;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarEmpleadoTCMMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarEmpleadoTCMMResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoTCMMResponseBody Body;
        
        public ConsultarEmpleadoTCMMResponse() {
        }
        
        public ConsultarEmpleadoTCMMResponse(Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoTCMMResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarEmpleadoTCMMResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Milano.BackEnd.Business.ProxyVentaEmpleado.InfoEmpleado ConsultarEmpleadoTCMMResult;
        
        public ConsultarEmpleadoTCMMResponseBody() {
        }
        
        public ConsultarEmpleadoTCMMResponseBody(Milano.BackEnd.Business.ProxyVentaEmpleado.InfoEmpleado ConsultarEmpleadoTCMMResult) {
            this.ConsultarEmpleadoTCMMResult = ConsultarEmpleadoTCMMResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsVentaEmpleadoSoapChannel : Milano.BackEnd.Business.ProxyVentaEmpleado.wsVentaEmpleadoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsVentaEmpleadoSoapClient : System.ServiceModel.ClientBase<Milano.BackEnd.Business.ProxyVentaEmpleado.wsVentaEmpleadoSoap>, Milano.BackEnd.Business.ProxyVentaEmpleado.wsVentaEmpleadoSoap {
        
        public wsVentaEmpleadoSoapClient() {
        }
        
        public wsVentaEmpleadoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsVentaEmpleadoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsVentaEmpleadoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsVentaEmpleadoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyVentaEmpleado.RealizarVentaResponse Milano.BackEnd.Business.ProxyVentaEmpleado.wsVentaEmpleadoSoap.RealizarVenta(Milano.BackEnd.Business.ProxyVentaEmpleado.RealizarVentaRequest request) {
            return base.Channel.RealizarVenta(request);
        }
        
        public Milano.BackEnd.Business.ProxyVentaEmpleado.InfoVenta RealizarVenta(int codigoEmpresa, string numeroNomina, int codigoTienda, int codigoCaja, double montoVenta, double montoFinanciado, string folioVenta, int codigoTransaccion, System.DateTime fechaVenta) {
            Milano.BackEnd.Business.ProxyVentaEmpleado.RealizarVentaRequest inValue = new Milano.BackEnd.Business.ProxyVentaEmpleado.RealizarVentaRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyVentaEmpleado.RealizarVentaRequestBody();
            inValue.Body.codigoEmpresa = codigoEmpresa;
            inValue.Body.numeroNomina = numeroNomina;
            inValue.Body.codigoTienda = codigoTienda;
            inValue.Body.codigoCaja = codigoCaja;
            inValue.Body.montoVenta = montoVenta;
            inValue.Body.montoFinanciado = montoFinanciado;
            inValue.Body.folioVenta = folioVenta;
            inValue.Body.codigoTransaccion = codigoTransaccion;
            inValue.Body.fechaVenta = fechaVenta;
            Milano.BackEnd.Business.ProxyVentaEmpleado.RealizarVentaResponse retVal = ((Milano.BackEnd.Business.ProxyVentaEmpleado.wsVentaEmpleadoSoap)(this)).RealizarVenta(inValue);
            return retVal.Body.RealizarVentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoResponse Milano.BackEnd.Business.ProxyVentaEmpleado.wsVentaEmpleadoSoap.ConsultarEmpleado(Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoRequest request) {
            return base.Channel.ConsultarEmpleado(request);
        }
        
        public Milano.BackEnd.Business.ProxyVentaEmpleado.InfoEmpleado ConsultarEmpleado(int codigoEmpresa, string numeroNomina, int codigoTienda, int codigoCaja) {
            Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoRequest inValue = new Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoRequestBody();
            inValue.Body.codigoEmpresa = codigoEmpresa;
            inValue.Body.numeroNomina = numeroNomina;
            inValue.Body.codigoTienda = codigoTienda;
            inValue.Body.codigoCaja = codigoCaja;
            Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoResponse retVal = ((Milano.BackEnd.Business.ProxyVentaEmpleado.wsVentaEmpleadoSoap)(this)).ConsultarEmpleado(inValue);
            return retVal.Body.ConsultarEmpleadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoTCMMResponse Milano.BackEnd.Business.ProxyVentaEmpleado.wsVentaEmpleadoSoap.ConsultarEmpleadoTCMM(Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoTCMMRequest request) {
            return base.Channel.ConsultarEmpleadoTCMM(request);
        }
        
        public Milano.BackEnd.Business.ProxyVentaEmpleado.InfoEmpleado ConsultarEmpleadoTCMM(int codigoEmpresa, string numeroNomina, int codigoTienda, int codigoCaja) {
            Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoTCMMRequest inValue = new Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoTCMMRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoTCMMRequestBody();
            inValue.Body.codigoEmpresa = codigoEmpresa;
            inValue.Body.numeroNomina = numeroNomina;
            inValue.Body.codigoTienda = codigoTienda;
            inValue.Body.codigoCaja = codigoCaja;
            Milano.BackEnd.Business.ProxyVentaEmpleado.ConsultarEmpleadoTCMMResponse retVal = ((Milano.BackEnd.Business.ProxyVentaEmpleado.wsVentaEmpleadoSoap)(this)).ConsultarEmpleadoTCMM(inValue);
            return retVal.Body.ConsultarEmpleadoTCMMResult;
        }
    }
}
