//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milano.BackEnd.Business.ProxyTipoCambio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyTipoCambio.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetRate(System.Xml.XmlNode input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sale", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Sale(System.Xml.XmlNode input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InitializeMerchant", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode InitializeMerchant(System.Xml.XmlNode input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllowedMunicipalities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAllowedMunicipalities(System.Xml.XmlNode input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Void", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Void(System.Xml.XmlNode input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifySale", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode VerifySale(System.Xml.XmlNode input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyVoid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode VerifyVoid(System.Xml.XmlNode input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetBuyExchangeRate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode SetBuyExchangeRate(System.Xml.XmlNode input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Milano.BackEnd.Business.ProxyTipoCambio.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Milano.BackEnd.Business.ProxyTipoCambio.Service1Soap>, Milano.BackEnd.Business.ProxyTipoCambio.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode GetRate(System.Xml.XmlNode input) {
            return base.Channel.GetRate(input);
        }
        
        public System.Xml.XmlNode Sale(System.Xml.XmlNode input) {
            return base.Channel.Sale(input);
        }
        
        public System.Xml.XmlNode InitializeMerchant(System.Xml.XmlNode input) {
            return base.Channel.InitializeMerchant(input);
        }
        
        public System.Xml.XmlNode GetAllowedMunicipalities(System.Xml.XmlNode input) {
            return base.Channel.GetAllowedMunicipalities(input);
        }
        
        public System.Xml.XmlNode Void(System.Xml.XmlNode input) {
            return base.Channel.Void(input);
        }
        
        public System.Xml.XmlNode VerifySale(System.Xml.XmlNode input) {
            return base.Channel.VerifySale(input);
        }
        
        public System.Xml.XmlNode VerifyVoid(System.Xml.XmlNode input) {
            return base.Channel.VerifyVoid(input);
        }
        
        public System.Xml.XmlNode SetBuyExchangeRate(System.Xml.XmlNode input) {
            return base.Channel.SetBuyExchangeRate(input);
        }
    }
}
