//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milano.BackEnd.Business.ProxyTiempoAire {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long transaction_idField;
        
        private int rcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rcode_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string op_accountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string op_authorizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Milano.BackEnd.Business.ProxyTiempoAire.PrintData[] printDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xmlDevDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long transaction_id {
            get {
                return this.transaction_idField;
            }
            set {
                if ((this.transaction_idField.Equals(value) != true)) {
                    this.transaction_idField = value;
                    this.RaisePropertyChanged("transaction_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int rcode {
            get {
                return this.rcodeField;
            }
            set {
                if ((this.rcodeField.Equals(value) != true)) {
                    this.rcodeField = value;
                    this.RaisePropertyChanged("rcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rcode_description {
            get {
                return this.rcode_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.rcode_descriptionField, value) != true)) {
                    this.rcode_descriptionField = value;
                    this.RaisePropertyChanged("rcode_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string op_account {
            get {
                return this.op_accountField;
            }
            set {
                if ((object.ReferenceEquals(this.op_accountField, value) != true)) {
                    this.op_accountField = value;
                    this.RaisePropertyChanged("op_account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string op_authorization {
            get {
                return this.op_authorizationField;
            }
            set {
                if ((object.ReferenceEquals(this.op_authorizationField, value) != true)) {
                    this.op_authorizationField = value;
                    this.RaisePropertyChanged("op_authorization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Milano.BackEnd.Business.ProxyTiempoAire.PrintData[] printData {
            get {
                return this.printDataField;
            }
            set {
                if ((object.ReferenceEquals(this.printDataField, value) != true)) {
                    this.printDataField = value;
                    this.RaisePropertyChanged("printData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string xmlDevData {
            get {
                return this.xmlDevDataField;
            }
            set {
                if ((object.ReferenceEquals(this.xmlDevDataField, value) != true)) {
                    this.xmlDevDataField = value;
                    this.RaisePropertyChanged("xmlDevData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrintData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PrintData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_labelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_dataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string m_label {
            get {
                return this.m_labelField;
            }
            set {
                if ((object.ReferenceEquals(this.m_labelField, value) != true)) {
                    this.m_labelField = value;
                    this.RaisePropertyChanged("m_label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string m_data {
            get {
                return this.m_dataField;
            }
            set {
                if ((object.ReferenceEquals(this.m_dataField, value) != true)) {
                    this.m_dataField = value;
                    this.RaisePropertyChanged("m_data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Milano.BackEnd.Business.ProxyTiempoAire.Form))]
    public partial class InfoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int m_moduleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Milano.BackEnd.Business.ProxyTiempoAire.ArrayOfElement m_formField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xmlDevDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int m_moduleId {
            get {
                return this.m_moduleIdField;
            }
            set {
                if ((this.m_moduleIdField.Equals(value) != true)) {
                    this.m_moduleIdField = value;
                    this.RaisePropertyChanged("m_moduleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Milano.BackEnd.Business.ProxyTiempoAire.ArrayOfElement m_form {
            get {
                return this.m_formField;
            }
            set {
                if ((object.ReferenceEquals(this.m_formField, value) != true)) {
                    this.m_formField = value;
                    this.RaisePropertyChanged("m_form");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlDevData {
            get {
                return this.xmlDevDataField;
            }
            set {
                if ((object.ReferenceEquals(this.xmlDevDataField, value) != true)) {
                    this.xmlDevDataField = value;
                    this.RaisePropertyChanged("xmlDevData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Form", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Form : Milano.BackEnd.Business.ProxyTiempoAire.InfoResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfElement", Namespace="http://tempuri.org/", ItemName="element")]
    [System.SerializableAttribute()]
    public class ArrayOfElement : System.Collections.Generic.List<Milano.BackEnd.Business.ProxyTiempoAire.element> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="element", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class element : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Milano.BackEnd.Business.ProxyTiempoAire.elementType m_eTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_valueField;
        
        private bool m_readonlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Milano.BackEnd.Business.ProxyTiempoAire.inputElement m_inputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Milano.BackEnd.Business.ProxyTiempoAire.selectElement m_selectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Milano.BackEnd.Business.ProxyTiempoAire.elementType m_eType {
            get {
                return this.m_eTypeField;
            }
            set {
                if ((this.m_eTypeField.Equals(value) != true)) {
                    this.m_eTypeField = value;
                    this.RaisePropertyChanged("m_eType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string m_name {
            get {
                return this.m_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.m_nameField, value) != true)) {
                    this.m_nameField = value;
                    this.RaisePropertyChanged("m_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string m_value {
            get {
                return this.m_valueField;
            }
            set {
                if ((object.ReferenceEquals(this.m_valueField, value) != true)) {
                    this.m_valueField = value;
                    this.RaisePropertyChanged("m_value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool m_readonly {
            get {
                return this.m_readonlyField;
            }
            set {
                if ((this.m_readonlyField.Equals(value) != true)) {
                    this.m_readonlyField = value;
                    this.RaisePropertyChanged("m_readonly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Milano.BackEnd.Business.ProxyTiempoAire.inputElement m_input {
            get {
                return this.m_inputField;
            }
            set {
                if ((object.ReferenceEquals(this.m_inputField, value) != true)) {
                    this.m_inputField = value;
                    this.RaisePropertyChanged("m_input");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Milano.BackEnd.Business.ProxyTiempoAire.selectElement m_select {
            get {
                return this.m_selectField;
            }
            set {
                if ((object.ReferenceEquals(this.m_selectField, value) != true)) {
                    this.m_selectField = value;
                    this.RaisePropertyChanged("m_select");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="inputElement", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class inputElement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Milano.BackEnd.Business.ProxyTiempoAire.iType m_iTypeField;
        
        private int m_iMinValueField;
        
        private int m_iMaxValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Milano.BackEnd.Business.ProxyTiempoAire.iType m_iType {
            get {
                return this.m_iTypeField;
            }
            set {
                if ((this.m_iTypeField.Equals(value) != true)) {
                    this.m_iTypeField = value;
                    this.RaisePropertyChanged("m_iType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int m_iMinValue {
            get {
                return this.m_iMinValueField;
            }
            set {
                if ((this.m_iMinValueField.Equals(value) != true)) {
                    this.m_iMinValueField = value;
                    this.RaisePropertyChanged("m_iMinValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int m_iMaxValue {
            get {
                return this.m_iMaxValueField;
            }
            set {
                if ((this.m_iMaxValueField.Equals(value) != true)) {
                    this.m_iMaxValueField = value;
                    this.RaisePropertyChanged("m_iMaxValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="selectElement", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class selectElement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Milano.BackEnd.Business.ProxyTiempoAire.ArrayOfOption m_optionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Milano.BackEnd.Business.ProxyTiempoAire.ArrayOfOption m_options {
            get {
                return this.m_optionsField;
            }
            set {
                if ((object.ReferenceEquals(this.m_optionsField, value) != true)) {
                    this.m_optionsField = value;
                    this.RaisePropertyChanged("m_options");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="elementType", Namespace="http://tempuri.org/")]
    public enum elementType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        input = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        select = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="iType", Namespace="http://tempuri.org/")]
    public enum iType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        texto = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        numero = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        dinero = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        password = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        submit = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fecha = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfOption", Namespace="http://tempuri.org/", ItemName="option")]
    [System.SerializableAttribute()]
    public class ArrayOfOption : System.Collections.Generic.List<Milano.BackEnd.Business.ProxyTiempoAire.option> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="option", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class option : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_valueField;
        
        private float m_amountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string m_text {
            get {
                return this.m_textField;
            }
            set {
                if ((object.ReferenceEquals(this.m_textField, value) != true)) {
                    this.m_textField = value;
                    this.RaisePropertyChanged("m_text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string m_value {
            get {
                return this.m_valueField;
            }
            set {
                if ((object.ReferenceEquals(this.m_valueField, value) != true)) {
                    this.m_valueField = value;
                    this.RaisePropertyChanged("m_value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float m_amount {
            get {
                return this.m_amountField;
            }
            set {
                if ((this.m_amountField.Equals(value) != true)) {
                    this.m_amountField = value;
                    this.RaisePropertyChanged("m_amount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DevInfoResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DevInfoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Milano.BackEnd.Business.ProxyTiempoAire.DeviceManager m_deviceManagerIdField;
        
        private int m_moduleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xmlDevDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Milano.BackEnd.Business.ProxyTiempoAire.DeviceManager m_deviceManagerId {
            get {
                return this.m_deviceManagerIdField;
            }
            set {
                if ((this.m_deviceManagerIdField.Equals(value) != true)) {
                    this.m_deviceManagerIdField = value;
                    this.RaisePropertyChanged("m_deviceManagerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int m_moduleId {
            get {
                return this.m_moduleIdField;
            }
            set {
                if ((this.m_moduleIdField.Equals(value) != true)) {
                    this.m_moduleIdField = value;
                    this.RaisePropertyChanged("m_moduleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string xmlDevData {
            get {
                return this.xmlDevDataField;
            }
            set {
                if ((object.ReferenceEquals(this.xmlDevDataField, value) != true)) {
                    this.xmlDevDataField = value;
                    this.RaisePropertyChanged("xmlDevData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceManager", Namespace="http://tempuri.org/")]
    public enum DeviceManager : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ComponenteG21 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CuentaExpressBBVA = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedEfectiva = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BancomerTS = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyTiempoAire.transactSoap")]
    public interface transactSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTRequestID", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestIDResponse GetTRequestID(Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestIDRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTRequestID_A", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestID_AResponse GetTRequestID_A(Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestID_ARequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TRequestID del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckTransaction", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyTiempoAire.CheckTransactionResponse CheckTransaction(Milano.BackEnd.Business.ProxyTiempoAire.CheckTransactionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TRequestID del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoT", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyTiempoAire.DoTResponse DoT(Milano.BackEnd.Business.ProxyTiempoAire.DoTRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSkuList", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyTiempoAire.GetSkuListResponse GetSkuList(Milano.BackEnd.Business.ProxyTiempoAire.GetSkuListRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalance", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyTiempoAire.GetBalanceResponse GetBalance(Milano.BackEnd.Business.ProxyTiempoAire.GetBalanceRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfo", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyTiempoAire.GetInfoResponse GetInfo(Milano.BackEnd.Business.ProxyTiempoAire.GetInfoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDevInfo", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyTiempoAire.GetDevInfoResponse GetDevInfo(Milano.BackEnd.Business.ProxyTiempoAire.GetDevInfoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento form del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/form2_xmlDevData", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyTiempoAire.form2_xmlDevDataResponse form2_xmlDevData(Milano.BackEnd.Business.ProxyTiempoAire.form2_xmlDevDataRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TRequestID del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoA", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyTiempoAire.DoAResponse DoA(Milano.BackEnd.Business.ProxyTiempoAire.DoARequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTRequestIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTRequestID", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestIDRequestBody Body;
        
        public GetTRequestIDRequest() {
        }
        
        public GetTRequestIDRequest(Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTRequestIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string licence;
        
        public GetTRequestIDRequestBody() {
        }
        
        public GetTRequestIDRequestBody(string username, string password, string licence) {
            this.username = username;
            this.password = password;
            this.licence = licence;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTRequestIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTRequestIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestIDResponseBody Body;
        
        public GetTRequestIDResponse() {
        }
        
        public GetTRequestIDResponse(Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTRequestIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTRequestIDResult;
        
        public GetTRequestIDResponseBody() {
        }
        
        public GetTRequestIDResponseBody(string GetTRequestIDResult) {
            this.GetTRequestIDResult = GetTRequestIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTRequestID_ARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTRequestID_A", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestID_ARequestBody Body;
        
        public GetTRequestID_ARequest() {
        }
        
        public GetTRequestID_ARequest(Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestID_ARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTRequestID_ARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string licence;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string authorization;
        
        public GetTRequestID_ARequestBody() {
        }
        
        public GetTRequestID_ARequestBody(string username, string password, string licence, string authorization) {
            this.username = username;
            this.password = password;
            this.licence = licence;
            this.authorization = authorization;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTRequestID_AResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTRequestID_AResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestID_AResponseBody Body;
        
        public GetTRequestID_AResponse() {
        }
        
        public GetTRequestID_AResponse(Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestID_AResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTRequestID_AResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTRequestID_AResult;
        
        public GetTRequestID_AResponseBody() {
        }
        
        public GetTRequestID_AResponseBody(string GetTRequestID_AResult) {
            this.GetTRequestID_AResult = GetTRequestID_AResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckTransaction", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.CheckTransactionRequestBody Body;
        
        public CheckTransactionRequest() {
        }
        
        public CheckTransactionRequest(Milano.BackEnd.Business.ProxyTiempoAire.CheckTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TRequestID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        public CheckTransactionRequestBody() {
        }
        
        public CheckTransactionRequestBody(string TRequestID, string username) {
            this.TRequestID = TRequestID;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckTransactionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.CheckTransactionResponseBody Body;
        
        public CheckTransactionResponse() {
        }
        
        public CheckTransactionResponse(Milano.BackEnd.Business.ProxyTiempoAire.CheckTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.TResponse CheckTransactionResult;
        
        public CheckTransactionResponseBody() {
        }
        
        public CheckTransactionResponseBody(Milano.BackEnd.Business.ProxyTiempoAire.TResponse CheckTransactionResult) {
            this.CheckTransactionResult = CheckTransactionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoT", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.DoTRequestBody Body;
        
        public DoTRequest() {
        }
        
        public DoTRequest(Milano.BackEnd.Business.ProxyTiempoAire.DoTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TRequestID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string skuCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string op_account;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public float monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Milano.BackEnd.Business.ProxyTiempoAire.Form form_addons;
        
        public DoTRequestBody() {
        }
        
        public DoTRequestBody(string TRequestID, string username, string skuCode, string op_account, float monto, Milano.BackEnd.Business.ProxyTiempoAire.Form form_addons) {
            this.TRequestID = TRequestID;
            this.username = username;
            this.skuCode = skuCode;
            this.op_account = op_account;
            this.monto = monto;
            this.form_addons = form_addons;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoTResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.DoTResponseBody Body;
        
        public DoTResponse() {
        }
        
        public DoTResponse(Milano.BackEnd.Business.ProxyTiempoAire.DoTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.TResponse DoTResult;
        
        public DoTResponseBody() {
        }
        
        public DoTResponseBody(Milano.BackEnd.Business.ProxyTiempoAire.TResponse DoTResult) {
            this.DoTResult = DoTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSkuListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSkuList", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.GetSkuListRequestBody Body;
        
        public GetSkuListRequest() {
        }
        
        public GetSkuListRequest(Milano.BackEnd.Business.ProxyTiempoAire.GetSkuListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSkuListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetSkuListRequestBody() {
        }
        
        public GetSkuListRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSkuListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSkuListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.GetSkuListResponseBody Body;
        
        public GetSkuListResponse() {
        }
        
        public GetSkuListResponse(Milano.BackEnd.Business.ProxyTiempoAire.GetSkuListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSkuListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSkuListResult;
        
        public GetSkuListResponseBody() {
        }
        
        public GetSkuListResponseBody(string GetSkuListResult) {
            this.GetSkuListResult = GetSkuListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalance", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.GetBalanceRequestBody Body;
        
        public GetBalanceRequest() {
        }
        
        public GetBalanceRequest(Milano.BackEnd.Business.ProxyTiempoAire.GetBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetBalanceRequestBody() {
        }
        
        public GetBalanceRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.GetBalanceResponseBody Body;
        
        public GetBalanceResponse() {
        }
        
        public GetBalanceResponse(Milano.BackEnd.Business.ProxyTiempoAire.GetBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBalanceResult;
        
        public GetBalanceResponseBody() {
        }
        
        public GetBalanceResponseBody(string GetBalanceResult) {
            this.GetBalanceResult = GetBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfo", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.GetInfoRequestBody Body;
        
        public GetInfoRequest() {
        }
        
        public GetInfoRequest(Milano.BackEnd.Business.ProxyTiempoAire.GetInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string licence;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string skuCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string op_account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string xmlDevData;
        
        public GetInfoRequestBody() {
        }
        
        public GetInfoRequestBody(string username, string password, string licence, string skuCode, string op_account, string xmlDevData) {
            this.username = username;
            this.password = password;
            this.licence = licence;
            this.skuCode = skuCode;
            this.op_account = op_account;
            this.xmlDevData = xmlDevData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.GetInfoResponseBody Body;
        
        public GetInfoResponse() {
        }
        
        public GetInfoResponse(Milano.BackEnd.Business.ProxyTiempoAire.GetInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.InfoResponse GetInfoResult;
        
        public GetInfoResponseBody() {
        }
        
        public GetInfoResponseBody(Milano.BackEnd.Business.ProxyTiempoAire.InfoResponse GetInfoResult) {
            this.GetInfoResult = GetInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDevInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDevInfo", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.GetDevInfoRequestBody Body;
        
        public GetDevInfoRequest() {
        }
        
        public GetDevInfoRequest(Milano.BackEnd.Business.ProxyTiempoAire.GetDevInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDevInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string licence;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string skuCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int caja;
        
        public GetDevInfoRequestBody() {
        }
        
        public GetDevInfoRequestBody(string username, string password, string licence, string skuCode, int caja) {
            this.username = username;
            this.password = password;
            this.licence = licence;
            this.skuCode = skuCode;
            this.caja = caja;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDevInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDevInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.GetDevInfoResponseBody Body;
        
        public GetDevInfoResponse() {
        }
        
        public GetDevInfoResponse(Milano.BackEnd.Business.ProxyTiempoAire.GetDevInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDevInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.DevInfoResponse GetDevInfoResult;
        
        public GetDevInfoResponseBody() {
        }
        
        public GetDevInfoResponseBody(Milano.BackEnd.Business.ProxyTiempoAire.DevInfoResponse GetDevInfoResult) {
            this.GetDevInfoResult = GetDevInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class form2_xmlDevDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="form2_xmlDevData", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.form2_xmlDevDataRequestBody Body;
        
        public form2_xmlDevDataRequest() {
        }
        
        public form2_xmlDevDataRequest(Milano.BackEnd.Business.ProxyTiempoAire.form2_xmlDevDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class form2_xmlDevDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.InfoResponse form;
        
        public form2_xmlDevDataRequestBody() {
        }
        
        public form2_xmlDevDataRequestBody(Milano.BackEnd.Business.ProxyTiempoAire.InfoResponse form) {
            this.form = form;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class form2_xmlDevDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="form2_xmlDevDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.form2_xmlDevDataResponseBody Body;
        
        public form2_xmlDevDataResponse() {
        }
        
        public form2_xmlDevDataResponse(Milano.BackEnd.Business.ProxyTiempoAire.form2_xmlDevDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class form2_xmlDevDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string form2_xmlDevDataResult;
        
        public form2_xmlDevDataResponseBody() {
        }
        
        public form2_xmlDevDataResponseBody(string form2_xmlDevDataResult) {
            this.form2_xmlDevDataResult = form2_xmlDevDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoA", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.DoARequestBody Body;
        
        public DoARequest() {
        }
        
        public DoARequest(Milano.BackEnd.Business.ProxyTiempoAire.DoARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TRequestID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string op_authorization;
        
        public DoARequestBody() {
        }
        
        public DoARequestBody(string TRequestID, string username, string op_authorization) {
            this.TRequestID = TRequestID;
            this.username = username;
            this.op_authorization = op_authorization;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoAResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyTiempoAire.DoAResponseBody Body;
        
        public DoAResponse() {
        }
        
        public DoAResponse(Milano.BackEnd.Business.ProxyTiempoAire.DoAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DoAResult;
        
        public DoAResponseBody() {
        }
        
        public DoAResponseBody(string DoAResult) {
            this.DoAResult = DoAResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface transactSoapChannel : Milano.BackEnd.Business.ProxyTiempoAire.transactSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class transactSoapClient : System.ServiceModel.ClientBase<Milano.BackEnd.Business.ProxyTiempoAire.transactSoap>, Milano.BackEnd.Business.ProxyTiempoAire.transactSoap {
        
        public transactSoapClient() {
        }
        
        public transactSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public transactSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public transactSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public transactSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestIDResponse Milano.BackEnd.Business.ProxyTiempoAire.transactSoap.GetTRequestID(Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestIDRequest request) {
            return base.Channel.GetTRequestID(request);
        }
        
        public string GetTRequestID(string username, string password, string licence) {
            Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestIDRequest inValue = new Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestIDRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestIDRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.licence = licence;
            Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestIDResponse retVal = ((Milano.BackEnd.Business.ProxyTiempoAire.transactSoap)(this)).GetTRequestID(inValue);
            return retVal.Body.GetTRequestIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestID_AResponse Milano.BackEnd.Business.ProxyTiempoAire.transactSoap.GetTRequestID_A(Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestID_ARequest request) {
            return base.Channel.GetTRequestID_A(request);
        }
        
        public string GetTRequestID_A(string username, string password, string licence, string authorization) {
            Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestID_ARequest inValue = new Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestID_ARequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestID_ARequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.licence = licence;
            inValue.Body.authorization = authorization;
            Milano.BackEnd.Business.ProxyTiempoAire.GetTRequestID_AResponse retVal = ((Milano.BackEnd.Business.ProxyTiempoAire.transactSoap)(this)).GetTRequestID_A(inValue);
            return retVal.Body.GetTRequestID_AResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyTiempoAire.CheckTransactionResponse Milano.BackEnd.Business.ProxyTiempoAire.transactSoap.CheckTransaction(Milano.BackEnd.Business.ProxyTiempoAire.CheckTransactionRequest request) {
            return base.Channel.CheckTransaction(request);
        }
        
        public Milano.BackEnd.Business.ProxyTiempoAire.TResponse CheckTransaction(string TRequestID, string username) {
            Milano.BackEnd.Business.ProxyTiempoAire.CheckTransactionRequest inValue = new Milano.BackEnd.Business.ProxyTiempoAire.CheckTransactionRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyTiempoAire.CheckTransactionRequestBody();
            inValue.Body.TRequestID = TRequestID;
            inValue.Body.username = username;
            Milano.BackEnd.Business.ProxyTiempoAire.CheckTransactionResponse retVal = ((Milano.BackEnd.Business.ProxyTiempoAire.transactSoap)(this)).CheckTransaction(inValue);
            return retVal.Body.CheckTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyTiempoAire.DoTResponse Milano.BackEnd.Business.ProxyTiempoAire.transactSoap.DoT(Milano.BackEnd.Business.ProxyTiempoAire.DoTRequest request) {
            return base.Channel.DoT(request);
        }
        
        public Milano.BackEnd.Business.ProxyTiempoAire.TResponse DoT(string TRequestID, string username, string skuCode, string op_account, float monto, Milano.BackEnd.Business.ProxyTiempoAire.Form form_addons) {
            Milano.BackEnd.Business.ProxyTiempoAire.DoTRequest inValue = new Milano.BackEnd.Business.ProxyTiempoAire.DoTRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyTiempoAire.DoTRequestBody();
            inValue.Body.TRequestID = TRequestID;
            inValue.Body.username = username;
            inValue.Body.skuCode = skuCode;
            inValue.Body.op_account = op_account;
            inValue.Body.monto = monto;
            inValue.Body.form_addons = form_addons;
            Milano.BackEnd.Business.ProxyTiempoAire.DoTResponse retVal = ((Milano.BackEnd.Business.ProxyTiempoAire.transactSoap)(this)).DoT(inValue);
            return retVal.Body.DoTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyTiempoAire.GetSkuListResponse Milano.BackEnd.Business.ProxyTiempoAire.transactSoap.GetSkuList(Milano.BackEnd.Business.ProxyTiempoAire.GetSkuListRequest request) {
            return base.Channel.GetSkuList(request);
        }
        
        public string GetSkuList(string username, string password) {
            Milano.BackEnd.Business.ProxyTiempoAire.GetSkuListRequest inValue = new Milano.BackEnd.Business.ProxyTiempoAire.GetSkuListRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyTiempoAire.GetSkuListRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Milano.BackEnd.Business.ProxyTiempoAire.GetSkuListResponse retVal = ((Milano.BackEnd.Business.ProxyTiempoAire.transactSoap)(this)).GetSkuList(inValue);
            return retVal.Body.GetSkuListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyTiempoAire.GetBalanceResponse Milano.BackEnd.Business.ProxyTiempoAire.transactSoap.GetBalance(Milano.BackEnd.Business.ProxyTiempoAire.GetBalanceRequest request) {
            return base.Channel.GetBalance(request);
        }
        
        public string GetBalance(string username, string password) {
            Milano.BackEnd.Business.ProxyTiempoAire.GetBalanceRequest inValue = new Milano.BackEnd.Business.ProxyTiempoAire.GetBalanceRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyTiempoAire.GetBalanceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Milano.BackEnd.Business.ProxyTiempoAire.GetBalanceResponse retVal = ((Milano.BackEnd.Business.ProxyTiempoAire.transactSoap)(this)).GetBalance(inValue);
            return retVal.Body.GetBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyTiempoAire.GetInfoResponse Milano.BackEnd.Business.ProxyTiempoAire.transactSoap.GetInfo(Milano.BackEnd.Business.ProxyTiempoAire.GetInfoRequest request) {
            return base.Channel.GetInfo(request);
        }
        
        public Milano.BackEnd.Business.ProxyTiempoAire.InfoResponse GetInfo(string username, string password, string licence, string skuCode, string op_account, string xmlDevData) {
            Milano.BackEnd.Business.ProxyTiempoAire.GetInfoRequest inValue = new Milano.BackEnd.Business.ProxyTiempoAire.GetInfoRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyTiempoAire.GetInfoRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.licence = licence;
            inValue.Body.skuCode = skuCode;
            inValue.Body.op_account = op_account;
            inValue.Body.xmlDevData = xmlDevData;
            Milano.BackEnd.Business.ProxyTiempoAire.GetInfoResponse retVal = ((Milano.BackEnd.Business.ProxyTiempoAire.transactSoap)(this)).GetInfo(inValue);
            return retVal.Body.GetInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyTiempoAire.GetDevInfoResponse Milano.BackEnd.Business.ProxyTiempoAire.transactSoap.GetDevInfo(Milano.BackEnd.Business.ProxyTiempoAire.GetDevInfoRequest request) {
            return base.Channel.GetDevInfo(request);
        }
        
        public Milano.BackEnd.Business.ProxyTiempoAire.DevInfoResponse GetDevInfo(string username, string password, string licence, string skuCode, int caja) {
            Milano.BackEnd.Business.ProxyTiempoAire.GetDevInfoRequest inValue = new Milano.BackEnd.Business.ProxyTiempoAire.GetDevInfoRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyTiempoAire.GetDevInfoRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.licence = licence;
            inValue.Body.skuCode = skuCode;
            inValue.Body.caja = caja;
            Milano.BackEnd.Business.ProxyTiempoAire.GetDevInfoResponse retVal = ((Milano.BackEnd.Business.ProxyTiempoAire.transactSoap)(this)).GetDevInfo(inValue);
            return retVal.Body.GetDevInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyTiempoAire.form2_xmlDevDataResponse Milano.BackEnd.Business.ProxyTiempoAire.transactSoap.form2_xmlDevData(Milano.BackEnd.Business.ProxyTiempoAire.form2_xmlDevDataRequest request) {
            return base.Channel.form2_xmlDevData(request);
        }
        
        public string form2_xmlDevData(Milano.BackEnd.Business.ProxyTiempoAire.InfoResponse form) {
            Milano.BackEnd.Business.ProxyTiempoAire.form2_xmlDevDataRequest inValue = new Milano.BackEnd.Business.ProxyTiempoAire.form2_xmlDevDataRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyTiempoAire.form2_xmlDevDataRequestBody();
            inValue.Body.form = form;
            Milano.BackEnd.Business.ProxyTiempoAire.form2_xmlDevDataResponse retVal = ((Milano.BackEnd.Business.ProxyTiempoAire.transactSoap)(this)).form2_xmlDevData(inValue);
            return retVal.Body.form2_xmlDevDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyTiempoAire.DoAResponse Milano.BackEnd.Business.ProxyTiempoAire.transactSoap.DoA(Milano.BackEnd.Business.ProxyTiempoAire.DoARequest request) {
            return base.Channel.DoA(request);
        }
        
        public string DoA(string TRequestID, string username, string op_authorization) {
            Milano.BackEnd.Business.ProxyTiempoAire.DoARequest inValue = new Milano.BackEnd.Business.ProxyTiempoAire.DoARequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyTiempoAire.DoARequestBody();
            inValue.Body.TRequestID = TRequestID;
            inValue.Body.username = username;
            inValue.Body.op_authorization = op_authorization;
            Milano.BackEnd.Business.ProxyTiempoAire.DoAResponse retVal = ((Milano.BackEnd.Business.ProxyTiempoAire.transactSoap)(this)).DoA(inValue);
            return retVal.Body.DoAResult;
        }
    }
}
