//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milano.BackEnd.Business.ProxyCambioContrasenia {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCambioContrasenia.wsCambioPasswordSoap")]
    public interface wsCambioPasswordSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sNuevoPassword del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CambiarPassword", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyCambioContrasenia.CambiarPasswordResponse CambiarPassword(Milano.BackEnd.Business.ProxyCambioContrasenia.CambiarPasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambiarPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CambiarPassword", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyCambioContrasenia.CambiarPasswordRequestBody Body;
        
        public CambiarPasswordRequest() {
        }
        
        public CambiarPasswordRequest(Milano.BackEnd.Business.ProxyCambioContrasenia.CambiarPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CambiarPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigoTienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int codigoCaja;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int codigoEmpleado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sNuevoPassword;
        
        public CambiarPasswordRequestBody() {
        }
        
        public CambiarPasswordRequestBody(int codigoTienda, int codigoCaja, int codigoEmpleado, string sNuevoPassword) {
            this.codigoTienda = codigoTienda;
            this.codigoCaja = codigoCaja;
            this.codigoEmpleado = codigoEmpleado;
            this.sNuevoPassword = sNuevoPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambiarPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CambiarPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyCambioContrasenia.CambiarPasswordResponseBody Body;
        
        public CambiarPasswordResponse() {
        }
        
        public CambiarPasswordResponse(Milano.BackEnd.Business.ProxyCambioContrasenia.CambiarPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CambiarPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CambiarPasswordResult;
        
        public CambiarPasswordResponseBody() {
        }
        
        public CambiarPasswordResponseBody(string CambiarPasswordResult) {
            this.CambiarPasswordResult = CambiarPasswordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsCambioPasswordSoapChannel : Milano.BackEnd.Business.ProxyCambioContrasenia.wsCambioPasswordSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsCambioPasswordSoapClient : System.ServiceModel.ClientBase<Milano.BackEnd.Business.ProxyCambioContrasenia.wsCambioPasswordSoap>, Milano.BackEnd.Business.ProxyCambioContrasenia.wsCambioPasswordSoap {
        
        public wsCambioPasswordSoapClient() {
        }
        
        public wsCambioPasswordSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsCambioPasswordSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCambioPasswordSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCambioPasswordSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyCambioContrasenia.CambiarPasswordResponse Milano.BackEnd.Business.ProxyCambioContrasenia.wsCambioPasswordSoap.CambiarPassword(Milano.BackEnd.Business.ProxyCambioContrasenia.CambiarPasswordRequest request) {
            return base.Channel.CambiarPassword(request);
        }
        
        public string CambiarPassword(int codigoTienda, int codigoCaja, int codigoEmpleado, string sNuevoPassword) {
            Milano.BackEnd.Business.ProxyCambioContrasenia.CambiarPasswordRequest inValue = new Milano.BackEnd.Business.ProxyCambioContrasenia.CambiarPasswordRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyCambioContrasenia.CambiarPasswordRequestBody();
            inValue.Body.codigoTienda = codigoTienda;
            inValue.Body.codigoCaja = codigoCaja;
            inValue.Body.codigoEmpleado = codigoEmpleado;
            inValue.Body.sNuevoPassword = sNuevoPassword;
            Milano.BackEnd.Business.ProxyCambioContrasenia.CambiarPasswordResponse retVal = ((Milano.BackEnd.Business.ProxyCambioContrasenia.wsCambioPasswordSoap)(this)).CambiarPassword(inValue);
            return retVal.Body.CambiarPasswordResult;
        }
    }
}
