//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milano.BackEnd.Business.ProxyCapturaLuz {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCapturaLuz.wsCapturaDeLuzSoap")]
    public interface wsCapturaDeLuzSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CapturaAperturaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CapturaApertura", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyCapturaLuz.CapturaAperturaResponse CapturaApertura(Milano.BackEnd.Business.ProxyCapturaLuz.CapturaAperturaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CapturaCierreResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CapturaCierre", ReplyAction="*")]
        Milano.BackEnd.Business.ProxyCapturaLuz.CapturaCierreResponse CapturaCierre(Milano.BackEnd.Business.ProxyCapturaLuz.CapturaCierreRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CapturaAperturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CapturaApertura", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyCapturaLuz.CapturaAperturaRequestBody Body;
        
        public CapturaAperturaRequest() {
        }
        
        public CapturaAperturaRequest(Milano.BackEnd.Business.ProxyCapturaLuz.CapturaAperturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CapturaAperturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigoTienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int codigoCajero;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int codigoCaja;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal importe;
        
        public CapturaAperturaRequestBody() {
        }
        
        public CapturaAperturaRequestBody(int codigoTienda, int codigoCajero, int codigoCaja, System.DateTime fecha, decimal importe) {
            this.codigoTienda = codigoTienda;
            this.codigoCajero = codigoCajero;
            this.codigoCaja = codigoCaja;
            this.fecha = fecha;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CapturaAperturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CapturaAperturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyCapturaLuz.CapturaAperturaResponseBody Body;
        
        public CapturaAperturaResponse() {
        }
        
        public CapturaAperturaResponse(Milano.BackEnd.Business.ProxyCapturaLuz.CapturaAperturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CapturaAperturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CapturaAperturaResult;
        
        public CapturaAperturaResponseBody() {
        }
        
        public CapturaAperturaResponseBody(string CapturaAperturaResult) {
            this.CapturaAperturaResult = CapturaAperturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CapturaCierreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CapturaCierre", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyCapturaLuz.CapturaCierreRequestBody Body;
        
        public CapturaCierreRequest() {
        }
        
        public CapturaCierreRequest(Milano.BackEnd.Business.ProxyCapturaLuz.CapturaCierreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CapturaCierreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigoTienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int codigoCajero;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int codigoCaja;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal importeApertura;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal importeCierre;
        
        public CapturaCierreRequestBody() {
        }
        
        public CapturaCierreRequestBody(int codigoTienda, int codigoCajero, int codigoCaja, System.DateTime fecha, decimal importeApertura, decimal importeCierre) {
            this.codigoTienda = codigoTienda;
            this.codigoCajero = codigoCajero;
            this.codigoCaja = codigoCaja;
            this.fecha = fecha;
            this.importeApertura = importeApertura;
            this.importeCierre = importeCierre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CapturaCierreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CapturaCierreResponse", Namespace="http://tempuri.org/", Order=0)]
        public Milano.BackEnd.Business.ProxyCapturaLuz.CapturaCierreResponseBody Body;
        
        public CapturaCierreResponse() {
        }
        
        public CapturaCierreResponse(Milano.BackEnd.Business.ProxyCapturaLuz.CapturaCierreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CapturaCierreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CapturaCierreResult;
        
        public CapturaCierreResponseBody() {
        }
        
        public CapturaCierreResponseBody(string CapturaCierreResult) {
            this.CapturaCierreResult = CapturaCierreResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsCapturaDeLuzSoapChannel : Milano.BackEnd.Business.ProxyCapturaLuz.wsCapturaDeLuzSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsCapturaDeLuzSoapClient : System.ServiceModel.ClientBase<Milano.BackEnd.Business.ProxyCapturaLuz.wsCapturaDeLuzSoap>, Milano.BackEnd.Business.ProxyCapturaLuz.wsCapturaDeLuzSoap {
        
        public wsCapturaDeLuzSoapClient() {
        }
        
        public wsCapturaDeLuzSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsCapturaDeLuzSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCapturaDeLuzSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCapturaDeLuzSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyCapturaLuz.CapturaAperturaResponse Milano.BackEnd.Business.ProxyCapturaLuz.wsCapturaDeLuzSoap.CapturaApertura(Milano.BackEnd.Business.ProxyCapturaLuz.CapturaAperturaRequest request) {
            return base.Channel.CapturaApertura(request);
        }
        
        public string CapturaApertura(int codigoTienda, int codigoCajero, int codigoCaja, System.DateTime fecha, decimal importe) {
            Milano.BackEnd.Business.ProxyCapturaLuz.CapturaAperturaRequest inValue = new Milano.BackEnd.Business.ProxyCapturaLuz.CapturaAperturaRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyCapturaLuz.CapturaAperturaRequestBody();
            inValue.Body.codigoTienda = codigoTienda;
            inValue.Body.codigoCajero = codigoCajero;
            inValue.Body.codigoCaja = codigoCaja;
            inValue.Body.fecha = fecha;
            inValue.Body.importe = importe;
            Milano.BackEnd.Business.ProxyCapturaLuz.CapturaAperturaResponse retVal = ((Milano.BackEnd.Business.ProxyCapturaLuz.wsCapturaDeLuzSoap)(this)).CapturaApertura(inValue);
            return retVal.Body.CapturaAperturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Milano.BackEnd.Business.ProxyCapturaLuz.CapturaCierreResponse Milano.BackEnd.Business.ProxyCapturaLuz.wsCapturaDeLuzSoap.CapturaCierre(Milano.BackEnd.Business.ProxyCapturaLuz.CapturaCierreRequest request) {
            return base.Channel.CapturaCierre(request);
        }
        
        public string CapturaCierre(int codigoTienda, int codigoCajero, int codigoCaja, System.DateTime fecha, decimal importeApertura, decimal importeCierre) {
            Milano.BackEnd.Business.ProxyCapturaLuz.CapturaCierreRequest inValue = new Milano.BackEnd.Business.ProxyCapturaLuz.CapturaCierreRequest();
            inValue.Body = new Milano.BackEnd.Business.ProxyCapturaLuz.CapturaCierreRequestBody();
            inValue.Body.codigoTienda = codigoTienda;
            inValue.Body.codigoCajero = codigoCajero;
            inValue.Body.codigoCaja = codigoCaja;
            inValue.Body.fecha = fecha;
            inValue.Body.importeApertura = importeApertura;
            inValue.Body.importeCierre = importeCierre;
            Milano.BackEnd.Business.ProxyCapturaLuz.CapturaCierreResponse retVal = ((Milano.BackEnd.Business.ProxyCapturaLuz.wsCapturaDeLuzSoap)(this)).CapturaCierre(inValue);
            return retVal.Body.CapturaCierreResult;
        }
    }
}
